openapi: 3.0.0
paths:
  /public_api/v1/actions/get_action_status:
    post:
      tags:
      - Response Action
      summary: Get Action Status
      description: |-
        Retrieve the status of the requested actions according to the action ID.

        **Required license:** Cortex Cloud Runtime Security. In Cortex Cloud Posture Security, you need the Cortex Cloud Runtime Security add-on.
      operationId: postGetActionStatus
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                request_data:
                  type: object
                  description: A dictionary containing the API request fields.
                  properties:
                    group_action_id:
                      type: integer
                      description: Action ID of the selected request.
                  required:
                  - group_action_id
              required:
              - request_data
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  reply:
                    type: object
                    description: JSON object containing the query result.
                    properties:
                      data:
                        type: object
                        properties:
                          agent_id:
                            type: string
                            enum:
                            - PENDING
                            - IN_PROGRESS
                            - CANCELLED
                            - PENDING_ABORT
                            - ABORTED
                            - EXPIRED
                            - COMPLETED_PARTIAL
                            - COMPLETED_SUCCESSFULLY
                            - FAILED
                            - TIMEOUT
        '400':
          description: Bad Request. Got an invalid JSON.
          content:
            application/json:
              schema:
                type: object
                properties:
                  reply:
                    type: object
                    properties:
                      data:
                        type: object
                        description: JSON object containing the query result.
                        additionalProperties: {}
                      errorReasons:
                        type: object
                        description: Returns all error messages the agent returns to allow for easier analysis.
        '401':
          description: Unauthorized access. An issue occurred during authentication. This can indicate an incorrect key, id,
            or other invalid authentication parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  reply:
                    type: object
                    properties:
                      data:
                        type: object
                        description: JSON object containing the query result.
                        additionalProperties: {}
                      errorReasons:
                        type: object
                        description: Returns all error messages the agent returns to allow for easier analysis.
        '402':
          description: Unauthorized access. User does not have the required license type to run this API.
          content:
            application/json:
              schema:
                type: object
                properties:
                  reply:
                    type: object
                    properties:
                      data:
                        type: object
                        description: JSON object containing the query result.
                        additionalProperties: {}
                      errorReasons:
                        type: object
                        description: Returns all error messages the agent returns to allow for easier analysis.
        '403':
          description: Forbidden access. The provided API Key does not have the required RBAC permissions to run this API.
          content:
            application/json:
              schema:
                type: object
                properties:
                  reply:
                    type: object
                    properties:
                      data:
                        type: object
                        description: JSON object containing the query result.
                        additionalProperties: {}
                      errorReasons:
                        type: object
                        description: Returns all error messages the agent returns to allow for easier analysis.
        '500':
          description: Internal server error. A unified status for API communication type errors.
          content:
            application/json:
              schema:
                type: object
                properties:
                  reply:
                    type: object
                    properties:
                      data:
                        type: object
                        description: JSON object containing the query result.
                        additionalProperties: {}
                      errorReasons:
                        type: object
                        description: Returns all error messages the agent returns to allow for easier analysis.
