openapi: 3.0.0
paths:
  /public_api/v1/authentication-settings/get/metadata:
    post:
      tags:
      - Authentication settings
      summary: Get IdP metadata
      description: |-
        Get the metadata for all IdPs.

        You must have **Instance Administrator** permissions to run this endpoint.

        **Required license:** Cortex Cloud Runtime Security or Cortex Cloud Posture Management
      operationId: post-public_api-v1-authentication-settings-get-metadata
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                request_data:
                  type: object
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  reply:
                    type: object
                    properties:
                      sp_entity_id:
                        type: string
                      sp_logout_url:
                        type: string
                      sp_url:
                        type: string
                      tenant_id:
                        type: string
        '400':
          description: Bad Request. Got an invalid JSON.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '401':
          description: Unauthorized access. An issue occurred during authentication. This can indicate an incorrect key, id,
            or other invalid authentication parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '402':
          description: Unauthorized access. User does not have the required license type to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '403':
          description: Forbidden access. The provided API Key does not have the required RBAC permissions to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '500':
          description: Internal server error. A unified status for API communication type errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
