openapi: 3.0.0
paths:
  /public_api/v1/bioc/insert:
    post:
      tags:
      - BIOCs
      summary: Insert or update BIOCs
      description: |-
        Insert new BIOCs or update existing BIOCs.

        **Note:** The BIOC `rule_id` is tenant specific and can't be used across tenants. Inserting BIOCs with the same `rule_id` as an existing BIOC on that tenant will overwrite the existing BIOC.

        You must have **Instance Administrator** permissions to run this endpoint.
      operationId: post-public_api-v1-bioc-insert
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - request_data
              properties:
                request_data:
                  type: array
                  items:
                    type: object
                    properties:
                      rule_id:
                        type: integer
                        x-stoplight:
                          id: h3r08ebedr4go
                      name:
                        type: string
                        description: BIOC name.
                      type:
                        enum:
                        - OTHER
                        - PERSISTENCE
                        - EVASION
                        - TAMPERING
                        - FILE_TYPE_OBFUSCATION
                        - PRIVILEGE_ESCALATION
                        - CREDENTIAL_ACCESS
                        - LATERAL_MOVEMENT
                        - EXECUTION
                        - COLLECTION
                        - EXFILTRATION
                        - INFILTRATION
                        - DROPPER
                        - FILE_PRIVILEGE_MANIPULATION
                        - RECONNAISSANCE
                        - DISCOVERY
                        description: BIOC type.
                      severity:
                        enum:
                        - SEV_010_INFO
                        - SEV_020_LOW
                        - SEV_030_MEDIUM
                        - SEV_040_HIGH
                        description: BIOC severity.
                      comment:
                        type: string
                      status:
                        enum:
                        - enabled
                        - disabled
                        description: BIOC status.
                      is_xql:
                        type: boolean
                      indicator:
                        type: object
                        additionalProperties: 
                      mitre_tactic_id_and_name:
                        type: array
                        items:
                          type: string
                      mitre_technique_id_and_name:
                        type: array
                        items:
                          type: string
        required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  added_objects:
                    type: array
                    description: List of BIOC objects added.
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        status:
                          type: string
                  updated_objects:
                    type: array
                    description: List of BIOC objects updated.
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        status:
                          type: string
                  errors:
                    type: array
                    description: A list of errors.
                    items:
                      type: string
        '400':
          description: Bad Request. Got invalid JSON.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '401':
          description: Unauthorized access. An issue occurred during authentication. This can indicate an incorrect key, id,
            or other invalid authentication parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '402':
          description: Unauthorized access. User does not have the required license type to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '403':
          description: Forbidden access. The provided API Key does not have the required RBAC permissions to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '500':
          description: Internal server error. A unified status for API communication type errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
