openapi: 3.0.0
paths:
  /public_api/v1/correlations/delete:
    post:
      tags:
      - Correlation Rules
      summary: Delete Correlation Rules
      description: |-
        Delete correlation rules selected by filter.

        You must have **Instance Administrator** permissions to run this endpoint.
      operationId: post-public_api-v1-correlations-delete
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - request_data
              properties:
                request_data:
                  type: object
                  properties:
                    filters:
                      type: array
                      description: An array of filter fields.
                      items:
                        type: object
                        properties:
                          field:
                            type: string
                            enum:
                            - name
                            - severity
                            - xql_query
                            - is_enabled
                            - description
                            - alert_name
                            - alert_category
                            - alert_description
                            - alert_fields
                            - execution_mode
                            - search_window
                            - simple_schedule
                            - timezone
                            - crontab
                            - suppression_enabled
                            - suppression_duration
                            - suppression_fields
                            - dataset
                            - user_defined_severity
                            - user_defined_category
                            - mitre_defs
                            - investigation_query_link
                            - drilldown_query_timeframe
                            - mapping_strategy
                            - alert_domain
                            description: "Identifies the correlation rule field the filter is matching. Filters are based
                               on the following keywords:- `name`: Correlation rule name.- `severity`: Correlation
                               rule severity.- `xql_query`: Correlation rule XQL query.- `is_enabled`: Whether the
                               correlation rule is enabled or disabled.- `description`: Correlation rule description.
                              - `alert_name`: Alert name.- `alert_category`: Alert category.- `alert_description`:
                               Alert description.- `alert_fields`: Alert fields.- `execution_mode`: Whether execution
                               mode is scheduled or real time.- `search_window`: Amount of time for search window.
                              - `simple_schedule`: Correlation rule schedule.- `timezone`: Correlation rule timezone.
                              - `crontab`: Linux scheduling for correlation rule.- `suppression_enabled`: Whether suppression
                               is enabled for correlation rule.- `suppression_duration`: Duration of correlation rule
                               suppression.- `suppression_fields`: Suppression fields.- `dataset`: Correlation rule
                               dataset.- `user_defined_severity`: User-defined severity.- `user_defined_category`:
                               User-defined category.- `mitre_defs`: MITRE definitions.- `investigation_query_link`:
                               Investigation query link.- `drilldown_query_timeframe`: Whether the drilldown query timeframe
                               is query or alert.- `mapping_strategy`: Whether the mapping strategy is auto or custom.
                              - `alert_domain`: Alert domain."
                          operator:
                            type: string
                            enum:
                            - EQ
                            - IN
                            - GTE
                            - LTE
                            description: "Identifies the comparison operator you want to use for this filter. Valid keywords
                               are:`EQ`- `name`: String- `severity`: String- `xql_query`: String- `is_enabled`:
                               Boolean- `description`: String- `alert_name`: String- `alert_category`: String
                              - `alert_description`: String- `alert_fields`: String or dictionary- `execution_mode`:
                               String- `search_window`: String- `simple_schedule`: String- `timezone`: String
                              - `crontab`: String- `suppression_enabled`: Boolean- `suppression_duration`: String
                              - `dataset`: String- `user_defined_severity`: String- `user_defined_category`: String
                              - `investigation_query_link`: String- `drilldown_query_timeframe`: String- `mapping_strategy`:
                               String- `alert_domain`: String`IN`- `suppression_fields`: List of strings
                              - `mitre_defs`: List of strings"
                          value:
                            oneOf:
                            - type: string
                            - type: array
                              items: 
                            - type: boolean
                            - type: integer
                            description: |-
                              "Value that this filter must match. The contents of this field will differ depending
                               on the correlation rule field that you specified for this filter:- `name`, `xql_query`,
                               `description`, `alert_name`, `alert_description`, `alert_fields`, `suppression_duration`,
                               `dataset`, `user_defined_severity`, `user_defined_category`, `investigation_query_link`: String.
                              - `severity`: String, can be one of the following: `SEV_010_INFO`, `SEV_020_LOW`, `SEV_030_MEDIUM`,
                               `SEV_040_HIGH`- `is_enabled`: String, can be one of the following: `enabled` or `disabled`.
                              - `alert_category`: String, can be one of the following: `other`, `persistence`, `evasion`,
                               `tampering`, `file_type_obfuscation`, `privilege_escalation`, `credential_access`, `lateral_movement`,
                               `execution`, `collection`, `exfiltration`, `infiltration`, `dropper`, `file_privilege_manipulation`,
                               `reconnaissance`, `discovery`.- `alert_fields`: Dictionary.- `execution_mode`: String,
                               can be one of the following: `scheduled` or `real_time`.- `search_window`: String, for
                               example: "2 hours".- `simple_schedule`: String, for example: "5 minutes".- `timezone`:
                               String, for example: "Asia/Jerusalem".- `crontab`: String, for example: "*/10 * * *
                               *".- `suppression_enabled`: Boolean: `true` or `false`.- `suppression_fields`: List
                               of strings.- `mitre_defs`: List of strings or dictionary.- `drilldown_query_timeframe`:
                               String, can be one of the following: `query` or `alert`.- `mapping_strategy`: String,
                               can be one of the following: `auto` or `custom`.- `alert_domain`: String, can be one of
                               the following: `domain_security`, `domain_it`, `domain_hunting`."
        required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  objects_count:
                    type: integer
                  objects:
                    type: array
                    items:
                      type: integer
        '400':
          description: Bad Request. Got invalid JSON.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '401':
          description: Unauthorized access. An issue occurred during authentication. This can indicate an incorrect key, id,
            or other invalid authentication parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '402':
          description: Unauthorized access. User does not have the required license type to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '403':
          description: Forbidden access. The provided API Key does not have the required RBAC permissions to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '500':
          description: Internal server error. A unified status for API communication type errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
