openapi: 3.0.0
paths:
  /public_api/v1/correlations/get:
    post:
      tags:
      - Correlation Rules
      summary: Get Correlation Rules
      description: "Return a list of correlation rules. You can return all correlation rules or filter results. You can also
        return extended results with all details included.- The response is concatenated using AND condition (OR is
        not supported).- The maximum result set size is >100.- Offset is the zero-based number of incidents from
        the start of the result set.You must have **Instance Administrator** permissions to run this endpoint."
      operationId: post-public_api-v1-correlations-get
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - request_data
              properties:
                request_data:
                  type: object
                  properties:
                    extended_view:
                      type: boolean
                    filters:
                      type: array
                      x-stoplight:
                        id: cb8wqmcyh0nbf
                      description: An array of filter fields.
                      items:
                        type: object
                        x-stoplight:
                          id: 0az8gyy0g35vz
                        properties:
                          field:
                            x-stoplight:
                              id: nu6rk76nwdw79
                            enum:
                            - name
                            - severity
                            - xql_query
                            - is_enabled
                            - description
                            - alert_name
                            - alert_category
                            - alert_description
                            - alert_fields
                            - execution_mode
                            - search_window
                            - simple_schedule
                            - timezone
                            - crontab
                            - suppression_enabled
                            - suppression_duration
                            - suppression_fields
                            - dataset
                            - user_defined_severity
                            - user_defined_category
                            - mitre_defs
                            - investigation_query_link
                            - drilldown_query_timeframe
                            - mapping_strategy
                            - alert_domain
                            description: "Identifies the correlation rule field the filter is matching. Filters are based
                               on the following keywords:- `name`: Correlation rule name.- `severity`: Correlation
                               rule severity.- `xql_query`: Correlation rule XQL query.- `is_enabled`: Whether the
                               correlation rule is enabled or disabled.- `description`: Correlation rule description.
                              - `alert_name`: Alert name.- `alert_category`: Alert category.- `alert_description`:
                               Alert description.- `alert_fields`: Alert fields.- `execution_mode`: Whether execution
                               mode is scheduled or real time.- `search_window`: Amount of time for search window.
                              - `simple_schedule`: Correlation rule schedule.- `timezone`: Correlation rule timezone.
                              - `crontab`: Linux scheduling for correlation rule.- `suppression_enabled`: Whether suppression
                               is enabled for correlation rule.- `suppression_duration`: Duration of correlation rule
                               suppression.- `suppression_fields`: Suppression fields.- `dataset`: Correlation rule
                               dataset.- `user_defined_severity`: User-defined severity.- `user_defined_category`:
                               User-defined category.- `mitre_defs`: MITRE definitions.- `investigation_query_link`:
                               Investigation query link.- `drilldown_query_timeframe`: Whether the drilldown query timeframe
                               is query or alert.- `mapping_strategy`: Whether the mapping strategy is auto or custom.
                              - `alert_domain`: Alert domain."
                          operator:
                            x-stoplight:
                              id: 30j7q4asbkekx
                            enum:
                            - EQ
                            - NEQ
                            - IN
                            - GTE
                            - LTE
                            description: "Identifies the comparison operator you want to use for this filter. Valid keywords
                               are:`EQ` / `NEQ`- `name`: String- `severity`: String- `xql_query`: String
                              - `is_enabled`: Boolean- `description`: String- `alert_name`: String- `alert_category`:
                               String- `alert_description`: String- `alert_fields`: String or dictionary- `execution_mode`:
                               String- `search_window`: String- `simple_schedule`: String- `timezone`: String
                              - `crontab`: String- `suppression_enabled`: Boolean- `suppression_duration`: String
                              - `dataset`: String- `user_defined_severity`: String- `user_defined_category`: String
                              - `investigation_query_link`: String- `drilldown_query_timeframe`: String- `mapping_strategy`:
                               String- `alert_domain`: String`IN`- `suppression_fields`: List of strings
                              - `mitre_defs`: List of strings"
                          value:
                            oneOf:
                            - type: string
                            - type: boolean
                            - type: array
                              items: 
                            x-stoplight:
                              id: b4k8ag5571dau
                            description: |-
                              "Value that this filter must match. The contents of this field will differ depending
                               on the correlation rule field that you specified for this filter:- `name`, `xql_query`,
                               `description`, `alert_name`, `alert_description`, `alert_fields`, `suppression_duration`,
                               `dataset`, `user_defined_severity`, `user_defined_category`, `investigation_query_link`: String.
                              - `severity`: String, can be one of the following: `SEV_010_INFO`, `SEV_020_LOW`, `SEV_030_MEDIUM`,
                               `SEV_040_HIGH`- `is_enabled`: String, can be one of the following: `enabled` or `disabled`.
                              - `alert_category`: String, can be one of the following: `other`, `persistence`, `evasion`,
                               `tampering`, `file_type_obfuscation`, `privilege_escalation`, `credential_access`, `lateral_movement`,
                               `execution`, `collection`, `exfiltration`, `infiltration`, `dropper`, `file_privilege_manipulation`,
                               `reconnaissance`, `discovery`.- `alert_fields`: Dictionary.- `execution_mode`: String,
                               can be one of the following: `scheduled` or `real_time`.- `search_window`: String, for
                               example: "2 hours".- `simple_schedule`: String, for example: "5 minutes".- `timezone`:
                               String, for example: "Asia/Jerusalem".- `crontab`: String, for example: "*/10 * * *
                               *".- `suppression_enabled`: Boolean: `true` or `false`.- `suppression_fields`: List
                               of strings.- `mitre_defs`: List of strings or dictionary.- `drilldown_query_timeframe`:
                               String, can be one of the following: `query` or `alert`.- `mapping_strategy`: String,
                               can be one of the following: `auto` or `custom`.- `alert_domain`: String, can be one of
                               the following: `domain_security`, `domain_it`, `domain_hunting`."
                    search_from:
                      type: integer
                      x-stoplight:
                        id: smo422mguxdbx
                      description: "Integer representing the starting offset within the query result set from which you want
                         correlation rules returned.Correlation rules are returned as a zero-based list. Any correlation
                         rule indexed less than this value is not returned in the final result set and defaults to zero."
                    search_to:
                      type: integer
                      x-stoplight:
                        id: 4ry5fitupvcoo
                      description: "Integer representing the end offset within the result set after which you do not want
                         BIOCs returned.BIOCs in the BIOC list that are indexed higher than this value are not returned
                         in the final results set. Defaults to >100, which returns all BIOCs to the end of the list."
        required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  objects_count:
                    type: integer
                  objects:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        severity:
                          type: string
                        xql_query:
                          type: string
                        is_enabled:
                          type: string
                        description:
                          type: string
                        alert_name:
                          type: string
                        alert_category:
                          type: string
                        alert_fields:
                          type: object
                          properties: 
                        execution_mode:
                          type: string
                        search_window:
                          type: string
                        simple_schedule:
                          type: string
                        timezone:
                          type: string
                        crontab:
                          type: string
                        suppression_enabled:
                          type: boolean
                        suppression_fields:
                          type: array
                          items:
                            type: string
                        dataset:
                          type: string
                        mitre_defs:
                          type: object
                          properties:
                            TA0005 - Defense Evasion:
                              type: array
                              items:
                                type: string
                        drilldown_query_timeframe:
                          type: string
                        mapping_strategy:
                          type: string
                  objects_type:
                    type: string
        '400':
          description: Bad Request. Got invalid JSON.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '401':
          description: Unauthorized access. An issue occurred during authentication. This can indicate an incorrect key, id,
            or other invalid authentication parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '402':
          description: Unauthorized access. User does not have the required license type to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '403':
          description: Forbidden access. The provided API Key does not have the required RBAC permissions to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '500':
          description: Internal server error. A unified status for API communication type errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
