openapi: 3.0.0
paths:
  /public_api/v1/dataset/get_created_datasets:
    post:
      tags:
      - XQL user datasets
      summary: Get created XQL user datasets
      description: "Retrieve a list of all XQL user datasets created using the Cortex SDK. **Required license:** Cortex
         Cloud Runtime Security or Cortex Cloud Posture Management These APIs are only applicable from within the
         XSIAM Notebook environment."
      operationId: post-public_api-v1-dataset-get_created_datasets
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  datasets:
                    type: array
                    description: A list of created datasets.
                    items:
                      type: string
