openapi: 3.0.0
paths:
  /public_api/v1/distributions/get_status:
    post:
      tags:
      - Endpoint Management
      summary: Get Distribution status
      description: |-
        Check the status of the installation package.

        **Required license:** Cortex Cloud Runtime Security. In Cortex Cloud Posture Security, you need the Cortex Cloud Runtime Security add-on.
      operationId: postGetStatus
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                request_data:
                  type: object
                  properties:
                    distribution_id:
                      type: string
                      description: The installation package ID.
                  required:
                  - distribution_id
              required:
              - request_data
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  reply:
                    type: object
                    properties:
                      status:
                        type: string
                        description: The status of the installation package.
        '400':
          description: Bad Request. Got an invalid JSON.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '401':
          description: Unauthorized access. An issue occurred during authentication. This can indicate an incorrect key, id,
            or other invalid authentication parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '402':
          description: Unauthorized access. User does not have the required license type to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '403':
          description: Forbidden access. The provided API Key does not have the required RBAC permissions to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '500':
          description: Internal server error. A unified status for API communication type errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
