openapi: 3.0.0
paths:
  /public_api/v1/endpoints/quarantine:
    post:
      tags:
      - Response Action
      summary: Quarantine Files
      description: |-
        Quarantine file on selected endpoints. You can select up to 1000 endpoints.

        Note: A success response means that the request reached the defined endpoints, however if the file was not found there, no quarantine action will take place. To ensure if the file has been quarantined, check the Cortex XDR Action Center.

        When filtering by multiple fields:
        - Response is concatenated using AND condition (OR is not supported).
        - Maximum result set size is 1000.
        - Offset is the zero-based number of cases from the start of the result set.

        **Required license:** Cortex Cloud Runtime Security. In Cortex Cloud Posture Security, you need the Cortex Cloud Runtime Security add-on.
      operationId: postQuarantine
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                request_data:
                  type: object
                  description: A dictionary containing the API request fields.
                  properties:
                    filters:
                      type: array
                      description: An array of filter fields.
                      items:
                        type: object
                        properties:
                          field:
                            type: string
                            enum:
                            - endpoint_id_list
                            description: |-
                              String that identifies a list the filters match. Filters are based on the following keywords:
                              - `endpoint_id_list`: List of endpoint IDs.
                          operator:
                            type: string
                            enum:
                            - in
                            description: |-
                              String that identifies the comparison operator you want to use for this filter. Valid keywords and values are:
                              `in`
                              - `endpoint_id_list`: List of strings
                          value:
                            type: array
                            description: |-
                              Value that this filter must match. Valid keywords:
                              - `endpoint_id_list`: Array of strings
                            items:
                              type: string
                        required:
                        - field
                        - operator
                        - value
                    file_path:
                      type: string
                      description: The path of the file you want to quarantine. You must enter a proper path and not symbolic
                        links.
                    file_hash:
                      type: string
                      description: |-
                        Case ID.
                        When included in the request, the **Quarantine File** action will appear in the **Cortex Cloud Case View Timeline** tab.
                  required:
                  - filters
                  - file_path
                  - file_hash
              required:
              - request_data
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  reply:
                    type: object
                    description: JSON object containing the query result.
                    properties:
                      action_id:
                        type: string
                        description: |-
                          ID of action to quarantine selected endpoints.
                          Response only indicates the request was successfully sent to the endpoint. To track if the file quarantine succeeded either:
                          - In Cortex XDR console, navigate to **Response** > **Action Center** and search for the action ID. Make sure the **Action ID** field is selected in the table **Layout** settings.
                          - Send a **Get Action Status** API request.
                      status:
                        type: string
                        description: |-
                          Integer representing whether the action:
                          - 1: succeeded
                          - 0: failed
                      endpoints_count:
                        type: string
                        description: Number of endpoints included in the request.
        '400':
          description: Bad Request. Got an invalid JSON.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '401':
          description: Unauthorized access. An issue occurred during authentication. This can indicate an incorrect key, id,
            or other invalid authentication parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '402':
          description: Unauthorized access. User does not have the required license type to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '403':
          description: Forbidden access. The provided API Key does not have the required RBAC permissions to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '500':
          description: Internal server error. A unified status for API communication type errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
