openapi: 3.0.0
paths:
  /public_api/v1/indicators/get:
    post:
      tags:
      - IOCs
      summary: Get Indicators (IOCs)
      description: "Get a list of IOCs. You can return all IOCs or filter results. You can also return extended results with
         all details included.- The response is concatenated using AND condition (OR is not supported).- The maximum
         result set size is >100.- Offset is the zero-based number of incidents from the start of the result set.
        You must have **Instance Administrator** permissions to run this endpoint."
      operationId: post-public_api-v1-indicators-get
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - request_data
              properties:
                request_data:
                  type: object
                  properties:
                    extended_view:
                      type: boolean
                    filters:
                      type: array
                      description: An array of filter fields.
                      items:
                        type: object
                        properties:
                          field:
                            type: string
                            enum:
                            - indicator
                            - type
                            - severity
                            - expiration_date
                            - default_expiration_enabled
                            - comment
                            - reputation
                            - reliability
                            description: "Identifies the IOC field the filter is matching. Filters are based on the following
                               keywords:- `indicator`: Indicator.- `type`: Indicator type.- `severity`: Indicator
                               severity.- `expiration_date`: Expiration date in epoch milliseconds.- `default_expiration_enabled`:
                               Whether the default expiration is enabled.- `comment`: Comment.- `reputation`: Reputation
                               level.- `reliability`: Reliability level."
                          operator:
                            type: string
                            enum:
                            - EQ
                            - NEQ
                            - IN
                            - GTE
                            - LTE
                            description: "Identifies the comparison operator you want to use for this filter. Valid keywords
                               are:`gte` / `lte`- `expiration_date`: Integer in timestamp epoch milliseconds
                              `EQ` / `NEQ`- `indicator`: String- `type`: String- `severity`: String- `default_expiration_enabled`:
                               Boolean- `comment`: String- `reputation`: String- `reliability`: String"
                          value:
                            oneOf:
                            - type: array
                              items: 
                            - type: integer
                            - type: string
                            - type: boolean
                            description: "Value that this filter must match. The contents of this field will differ depending
                               on the IOC field that you specified for this filter:- `indicator`, `comment`: String.- `type`: String, can be one of the following: `hash`, `ip`, `path`, `domain_name`, `filename`,
                               `mixed`.- `severity`: String, can be one of the following: `SEV_010_INFO`, `SEV_020_LOW`,
                               `SEV_030_MEDIUM`, `SEV_040_HIGH`- `expiration_date`: Integer representing the number of
                               milliseconds after the Unix epoch, UTC timezone.- `default_expiration_enabled`: Boolean
                               value: `true` or `false`.- `comment`: String.- `reputation`: String, can be one of
                               the following: `good`, `bad`, `suspicious`, `unknown`, `no_reputation`.- `reliability`:
                               String, can be one of the following: `A`, `B`, `C`, `D`, `E`, `F`, `G`."
                    search_from:
                      type: integer
                      x-stoplight:
                        id: bwucpfjankku9
                      description: "Integer representing the starting offset within the query result set from which you want
                         indicators returned.Indicators are returned as a zero-based list. Any indicator indexed less
                         than this value is not returned in the final result set and defaults to zero."
                    search_to:
                      type: integer
                      x-stoplight:
                        id: hs3rfeqr1suft
                      description: "Integer representing the end offset within the result set after which you do not want
                         indicators returned.Indicators in the indicator list that are indexed higher than this value
                         are not returned in the final results set. Defaults to >100, which returns all indicators to the
                         end of the list."
        required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  objects_count:
                    type: integer
                  objects:
                    type: array
                    items:
                      type: object
                      properties:
                        rule_id:
                          type: integer
                        indicator:
                          type: string
                        type:
                          type: string
                        severity:
                          type: string
                        expiration_date:
                          type: integer
                        comment:
                          type: string
                  objects_type:
                    type: string
        '400':
          description: Bad Request. Got invalid JSON.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '401':
          description: Unauthorized access. An issue occurred during authentication. This can indicate an incorrect key, id,
            or other invalid authentication parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '402':
          description: Unauthorized access. User does not have the required license type to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '403':
          description: Forbidden access. The provided API Key does not have the required RBAC permissions to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '500':
          description: Internal server error. A unified status for API communication type errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
