openapi: 3.0.0
paths:
  /public_api/v1/indicators/insert:
    post:
      tags:
      - IOCs
      summary: Insert or update IOCs
      description: |-
        Insert new IOCs or update existing IOCs.

        **Note:** The IOC `rule_id` is tenant specific and can't be used across tenants. Inserting IOCs with the same `rule_id` as an existing IOC on that tenant will overwrite the existing IOC.

        You must have **Instance Administrator** permissions to run this endpoint.
      operationId: post-public_api-v1-indicators-insert
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - request_data
              properties:
                request_data:
                  type: array
                  items:
                    type: object
                    properties:
                      rule_id:
                        type: number
                        x-stoplight:
                          id: pflchcfpw9cbg
                      indicator:
                        type: string
                      type:
                        enum:
                        - HASH
                        - IP
                        - PATH
                        - DOMAIN_NAME
                        - FILENAME
                        - MIXED
                      severity:
                        enum:
                        - SEV_010_INFO
                        - SEV_020_LOW
                        - SEV_030_MEDIUM
                        - SEV_040_HIGH
                      expiration_date:
                        type: integer
                      default_expiration_enabled:
                        type: boolean
                      comment:
                        type: string
                      reputation:
                        enum:
                        - GOOD
                        - BAD
                        - SUSPICIOUS
                        - UNKNOWN
                        - NO_REPUTATION
                      reliability:
                        enum:
                        - A
                        - B
                        - C
                        - D
                        - E
                        - F
                        - G
        required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  added_objects:
                    type: array
                    description: List of IOC objects added.
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        status:
                          type: string
                  updated_objects:
                    type: array
                    description: List of IOC objects updated.
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        status:
                          type: string
                  errors:
                    type: array
                    description: List of errors, if any.
                    items:
                      type: string
        '400':
          description: Bad Request. Got invalid JSON.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '401':
          description: Unauthorized access. An issue occurred during authentication. This can indicate an incorrect key, id,
            or other invalid authentication parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '402':
          description: Unauthorized access. User does not have the required license type to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '403':
          description: Forbidden access. The provided API Key does not have the required RBAC permissions to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '500':
          description: Internal server error. A unified status for API communication type errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
