openapi: 3.0.0
paths:
  /public_api/v1/playbooks/get:
    post:
      tags:
      - Playbooks
      summary: Get a playbook
      description: |2-
         Get a playbook by filtering based on its name or ID. The playbook's YAML is returned in a ZIP file.

         You must have **Instance Administrator** permissions to run this endpoint.
      operationId: post-public_api-v1-playbooks-get
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - request_data
              properties:
                request_data:
                  type: object
                  properties:
                    filter:
                      type: object
                      description: Filter fields.
                      x-stoplight:
                        id: kn1alb979r9vo
                      properties:
                        field:
                          enum:
                          - id
                          - name
                          description: "Identifies the playbook field the filter is matching. Filters are based on the following
                             keywords:- `name`: Playbook name- `id`: Playbook ID"
                        value:
                          type: string
                          description: Value that this filter must match.
      responses:
        '200':
          description: OK
          content: 
