openapi: 3.0.0
paths:
  /public_api/v1/quarantine/status:
    post:
      tags:
      - Response Action
      summary: Get Quarantine Status
      description: |-
        Retrieve the quarantine status for specified files.

        **Required license:** Cortex Cloud Runtime Security. In Cortex Cloud Posture Security, you need the Cortex Cloud Runtime Security add-on.
      operationId: postStatus
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                request_data:
                  type: object
                  properties:
                    files:
                      type: array
                      description: Array of endpoint IDs, filepaths, and file hash.
                      items:
                        type: object
                        properties:
                          endpoint_id:
                            type: string
                            description: Endpoint ID
                          file_path:
                            type: string
                            description: File hash. Must be a valid SHA256.
                          file_hash:
                            type: string
                            description: File path.
                  required:
                  - files
              required:
              - request_data
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  reply:
                    type: array
                    items:
                      type: object
                      properties:
                        endpoint_id:
                          type: string
                          description: Endpoint ID.
                        file_path:
                          type: string
                          description: File path.
                        file_hash:
                          type: string
                          description: File hash.
                        status:
                          type: boolean
                          description: |-
                            The file's status.
                            True: The file is quarantined.
                            False: The file is not quarantined.
        '400':
          description: Bad Request. Got an invalid JSON.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '401':
          description: Unauthorized access. An issue occurred during authentication. This can indicate an incorrect key, id,
            or other invalid authentication parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '402':
          description: Unauthorized access. User does not have the required license type to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '403':
          description: Forbidden access. The provided API Key does not have the required RBAC permissions to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '500':
          description: Internal server error. A unified status for API communication type errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
