openapi: 3.0.0
paths:
  /public_api/v1/scripts/insert:
    post:
      tags:
      - Scripts
      summary: Insert or update a script
      description: |-
        Update or add a script by passing the YAML in a ZIP file.

        You must have **Instance Administrator** permissions to run this endpoint.
      operationId: post-public_api-v1-scripts-insert
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  x-stoplight:
                    id: omp1s9jvwfy3v
                  format: binary
                  description: The script in YAML in a zipped file.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  objects_count:
                    type: integer
                    description: The number of scripts identified and attempted to be added.
                  objects:
                    type: object
                    properties:
                      failures_items:
                        type: array
                        description: This field in the response indicates that the script IDs listed failed to be added.
                        items:
                          type: object
                          properties:
                            error:
                              type: string
                              description: Error message.
                            id:
                              type: string
                              description: Script ID of the script that failed to be added.
