openapi: 3.0.0
paths:
  /public_api/v1/scripts/get_script_execution_status:
    post:
      tags:
      - Script execution
      summary: Get Script Execution Status
      description: |-
        Retrieve the status of a script execution action.

        **Required license:** Cortex Cloud Runtime Security or Cortex Cloud Posture Management
      operationId: postGetScriptExecutionStatus
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                request_data:
                  type: object
                  description: A dictionary containing the API request fields.
                  properties:
                    action_id:
                      type: string
                      description: Identifier of the action, can be found in Cortex XDR console **Response** > **Action Center**
                        > **Action ID** field.
                  required:
                  - action_id
              required:
              - request_data
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  reply:
                    type: object
                    description: JSON object containing the query result.
                    properties:
                      general_status:
                        type: string
                        description: General status of the action, considering the status of all the endpoints.
                      endpoints_pending:
                        type: integer
                        description: Number of endpoints in pending status.
                      endpoints_canceled:
                        type: integer
                        description: Number of endpoints in 'canceled' status.
                      endpoints_in_progress:
                        type: integer
                        description: Number of endpoints in 'in progress' status.
                      endpoints_timeout:
                        type: integer
                        description: Number of endpoints in 'timeout' status.
                      endpoints_failed:
                        type: integer
                        description: Number of endpoints in 'failed' status.
                      endpoints_completed_successfully:
                        type: integer
                        description: Number of endpoints in 'completed successfully' status.
                      endpoints_pending_abort:
                        type: integer
                        description: Number of endpoints in 'pending abort' status.
                      endpoints_aborted:
                        type: integer
                        description: Number of endpoints in 'aborted' status.
                      endpoints_expired:
                        type: integer
                        description: Number of endpoints in 'expired' status.
                      error_message:
                        type: string
                        description: Error message regarding permissions for running APIs or stating that the action doesn’t
                          exist.
        '400':
          description: Bad Request. Got an invalid JSON.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '401':
          description: Unauthorized access. An issue occurred during authentication. This can indicate an incorrect key, id,
            or other invalid authentication parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '402':
          description: Unauthorized access. User does not have the required license type to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '403':
          description: Forbidden access. The provided API Key does not have the required RBAC permissions to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '500':
          description: Internal server error. A unified status for API communication type errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
