openapi: 3.0.0
paths:
  /public_api/v1/xql/get_query_results:
    post:
      tags:
      - XQL query
      summary: Get XQL query results
      description: "Retrieve results of an executed XQL query API. Note: This endpoint only works on XQL queries initiated
         by `/public_api/v1/xql/start_xql_query/`.Maximum result set size is 1000. The API does not support pagination,
         therefore, you can set values to determine the result size limitation and how to wait for the results. To view response
         with greater than 1000 results you must call **Get XQL query results Stream**.For more information on how to
         run XQL queries, see [*Running XQL query APIs*](https://cortex-panw.stoplight.io/docs/cortex-xsiam-1/90ay3tlx6l9dh-running-xql-query-ap-is).
        <!-- theme: info -->> #### Note>> To ensure you don't surpass your quota, Cortex Cloud allows you to run
         up to four API queries in parallel.**Required license:** Cortex Cloud Runtime Security or Cortex Cloud Posture
         Management"
      operationId: postGetQueryResults
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              type: object
              properties:
                request_data:
                  type: object
                  properties:
                    query_id:
                      type: string
                      description: |-
                        String representing the unique execution ID generated by the response to **Start an XQL query** API.
                        You can also enter the execution ID of a query generated in Cortex XDR and listed in the Query Center table.
                    pending_flag:
                      type: boolean
                      description: |-
                        Boolean flag indicating whether the API call should operate in synchronous/blocking mode, or in asynchronous/non-blocking mode. Valid Values:
                        - True (default): The call returns immediately with one of the following options:
                        1) PENDING status indicating query hasn't yet completed or results are not yet ready to be returned. Need to execute the API call again.
                        2) SUCCESS/FAIL status
                        - False: The API will block until query completes and results are ready to be returned.
                    limit:
                      type: integer
                      description: |-
                        Integer representing the maximum number of results to return.
                        If the 'limit' is not specified or if 'limit' is greater than 1000 and the query yields more than 1000 valid results, a `stream id` will be generated for use in the *Get XQL query results Stream** API.
                        In the context of multi-tenant investigations, when you specify the parameter value (x),
                        it will return x results across all tenants combined, rather than x results for each individual tenant.
                        For example, if there are y tenants participating in the investigation, the maximum number of results returned can be x*y (up to the limit of 1,000,000).
                    format:
                      type: string
                      enum:
                      - json
                      - csv
                      description: The type of response output.
                  required:
                  - query_id
              required:
              - request_data
              example:
                request_data:
                  query_id: 061880b4867446_4356_inv
                  pending_flag: true
                  limit: 100
                  format: json
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  reply:
                    type: object
                    properties:
                      status:
                        type: string
                      number_of_results:
                        type: integer
                      query_cost:
                        type: object
                        additionalProperties:
                          type: number
                      remaining_quota:
                        type: number
                      results:
                        type: object
                        properties:
                          data:
                            type: array
                            items:
                              type: object
                              properties:
                                event_id:
                                  type: string
                                agent_version:
                                  type: string
                                _product:
                                  type: string
                                _time:
                                  type: integer
                                _vendor:
                                  type: string
                                insert_timestamp:
                                  type: integer
                                agent_os_type:
                                  type: string
                                event_type:
                                  type: string
                                event_sub_type:
                                  type: string
        '400':
          description: Bad Request. Got an invalid JSON.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '401':
          description: Unauthorized access. An issue occurred during authentication. This can indicate an incorrect key, id,
            or other invalid authentication parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '402':
          description: Unauthorized access. User does not have the required license type to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '403':
          description: Forbidden access. The provided API Key does not have the required RBAC permissions to run this API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
        '500':
          description: Internal server error. A unified status for API communication type errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
