openapi: 3.0.0
paths:
  /public_api/v1/xql/lookups/get_data:
    post:
      tags:
      - Lookup Datasets
      summary: Get data from a lookup dataset
      description: "Get data from a lookup dataset according to the specified filter fields. All lookup entries matching any\
        \ of the filter blocks are returned. To match a filter block, a lookup entry must match all the specified fields as\
        \ if there were an `AND` operator between them. If no filters are specified, return all lookup entries. \r\n\r\n**Note:**\
        \ \r\n\r\n- The maximum number of entries returned is 10,000. \r\n- Requests time out after three minutes.\r\n\r\n\
        **Required license:** Cortex Cloud Runtime Security or Cortex Cloud Posture Management"
      operationId: post-public_api-v1-xql-lookups-get_data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                request_data:
                  type: object
                  properties:
                    dataset_name:
                      type: string
                      description: Name of the dataset to query.
                    filters:
                      type: array
                      description: "Key-value pairs of fields to query in a dataset. A lookup entry must match all the specified\
                        \ fields as if there were an `AND` operator between them.\r\nYou can use one or more fields, up to\
                        \ the number of fields in the schema."
                      items:
                        type: object
                        additionalProperties:
                          type: string
                    limit:
                      type: integer
                      description: The maximum number of results to return. If this is not specified, return all lookup entries
                        that match the filter criteria.
                  required:
                  - dataset_name
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    additionalProperties:
                      type: string
                  filter_count:
                    type: integer
                    description: Number of entries that match the filter.
                  total_count:
                    type: integer
                    description: Total number of entries.
